apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
        - image: sachindramaharjan/reverseproxy
          name: reverseproxy
          imagePullPolicy: Always
          resources:
            requests:
              memory: "540Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1024m"
          ports:
            - containerPort: 8080
      restartPolicy: Always
