apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
    version: v2
  name: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      service: reverseproxy
      version: v2
  template:
    metadata:
      labels:
        service: reverseproxy
        version: v2
    spec:
      containers:
        - image: sachindramaharjan/reverseproxy
          name: reverseproxy
          imagePullPolicy: Always
          resources:
            requests:
              memory: "540Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1024m"
          ports:
            - containerPort: 8080
      restartPolicy: Always
