language: minimal

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  - docker -v && docker-compose -v
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
#   - sudo chmod +x ./kubectl
#   - sudo mv ./kubectl /usr/local/bin/kubectl

install:
  - docker-compose -f course-02/exercises/udacity-deployment/docker/docker-compose-build.yaml build --parallel
