version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: sachindramaharjan/reverseproxy
  backend_user:
    build:
      context: ../../udacity-restapi-user
    image: sachindramaharjan/udacity-restapi-user
  backend_feed:
    build:
      context: ../../udacity-restapi-feed
    image: sachindramaharjan/udacity-restapi-feed
  frontend:
    build:
      context: ../../udacity-frontend
    image: sachindramaharjan/udacity-frontend:local
