apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
    - name: reverseproxy
  image: sachindramaharjan/reverseproxy
  imagePullPolicy: Always
  resources:
    request:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "1024Mi"
      cpu: "500m"
  ports:
    - containerPort: 8080
restartPolicy: Always
